### ISSUE TITLE
yet another API hook library: mollismerx/elfspy

### ISSUE THREAD

**Issue by 1138-4EB** [kubo/funchook#11]
Hi @kubo! You might want to add [mollismerx/elfspy](https://github.com/mollismerx/elfspy) to the [List of API Hook Libraries](https://github.com/kubo/funchook/wiki/List-of-API-Hook-Libraries)

**Comment by kubo** [comment]
Thanks! It was added.

off-topic.
You wrote the link to elfspy as `[URL](name)`. I fixed it to `[name](URL)`.
