### ISSUE TITLE
funchook won't build on alpine linux

### ISSUE THREAD

**Issue by drdavella** [kubo/funchook#12]
When I attempt to build funchook on Alpine linux I get the following error:

```
funchook_unix.c: In function 'funchook_strerror':
funchook_unix.c:455:33: error: 'sys_nerr' undeclared (first use in this function); did you mean 'stderr'?
     if (0 <= errnum && errnum < sys_nerr) {
                                 ^~~~~~~~
                                 stderr
funchook_unix.c:455:33: note: each undeclared identifier is reported only once for each function it appears in
funchook_unix.c:456:16: error: 'sys_errlist' undeclared (first use in this function)
         return sys_errlist[errnum];
                ^~~~~~~~~~~
```

If I remove these lines the package builds just fine. It seems like using `_sys_errlist` and `sys_errlist` is non-standard. Is there any reason not to just use `strerror` instead?

**Comment by drdavella** [comment]
Thanks very much for the response and the explanation! Is there a good way around this if you're not willing to include `strerror`? Could we possibly add a compile-time option for use cases where we don't expect `strerror` to be hooked?

**Comment by kubo** [comment]
I may add a compile-time option to implement `strerror` compatible with [musl](https://www.musl-libc.org/) by including http://git.musl-libc.org/cgit/musl/tree/src/errno/__strerror.h (MIT license code).
