### ISSUE TITLE
funchook_uninstall not completing

### ISSUE THREAD

**Issue by tnavda** [kubo/funchook#17]
macOS:  10.15.6
Xcode:  11.7

I am seeing something very strange when debug logging is enabled, there is no return of funchook_uninstall being logged.  So it almost seems as if something wrong is happening.  For instance, below, why is "Leave funchook_uninstall()" never showing up?  I'm ultimately trying to figure out a crash on unhooking and I suspect this has something to do with it.  Any thoughts?  I haven't updated the repos since 2019, not sure if there have been significant changes on the macOS side.

Enter funchook_uninstall(0x14d34c000, 0x0)
  unprotect memory 0x1755a0000 (size=4096, prot=read,write,exec) <- 0x1755a0dc0 (size=5)
  protect memory 0x1755a0000 (size=4096, prot=read,exec)
  unprotect page 0x1755fa000 (size=4096)
Enter funchook_uninstall(0x14d34d000, 0x0)
  unprotect memory 0x1755a0000 (size=4096, prot=read,write,exec) <- 0x1755a0eb0 (size=5)
  protect memory 0x1755a0000 (size=4096, prot=read,exec)
  unprotect page 0x1755fb000 (size=4096)
Enter funchook_uninstall(0x14d34e000, 0x0)
  unprotect memory 0x1731e7000 (size=4096, prot=read,write,exec) <- 0x1731e7160 (size=5)
  protect memory 0x1731e7000 (size=4096, prot=read,exec)
  unprotect page 0x1755fc000 (size=4096)

**Comment by tnavda** [comment]
Ah it looks like the call to log_end in uninstall is always passing NULL, so it just isn't logging the output.

**Comment by kubo** [comment]
Sorry for not replying to you for so long time.
It seems to be fixed by the commit on 21 Jan 2020.
