### ISSUE TITLE
Ubuntu: hooking freetype io

### ISSUE THREAD

**Issue by Cpasjuste** [kubo/funchook#23]
Hi there,

I'm actually [hooking io stuff in my project](https://github.com/Cpasjuste/libcross2d/blob/romfs2/source/skeleton/romfs/romfs.cpp) (open/fopen, close/fclose, read/fread, lseek/fseek...) to provide a "romfs" layer on linux as on some handled consoles (vita, switch, 3ds..) for a multi-platform library.

This is working very fine for everything i have tested with this hooks, but i do have problem with the freetype library. Loading a new font with the hooks in place (fopen/fseek/ftell) is not working with the ubuntu "system freetype library" (that comes with apt), but it works fine when i compile the same version myself. The main difference i can see is when it works (with my own compiled freetype dynamic library) the "load font function" (FT_New_Face) do a call to "fopen" while the ubuntu one directly call the "open" function. 

I guess it's not a bug in funchook, but my question is to know if there could be some sort of protection or whatever on the ubuntu libs, as it seems fopen hook is not called on this one.

Else, many thanks for the great project :)
cpasjuste.

Edit: i did found that when compiling my project (and so freetype) in debug mode, it's working fine, but as soon as i compile it in release mode the hooking doesn't occur.

Edit2: i did found that hooking "__fxstat" instead "fstat" does make all working fine, i'm not sure what's the problem thought.

**Comment by kubo** [comment]
In https://www.freetype.org/freetype2/docs/design/design-4.html
> As an example, the default implementation of streams is located in the file `src/base/ftsystem.c` and uses the ANSI functions `fopen`, `fseek`, and `fread`. However, the Unix build of FreeType 2 provides an alternative implementation that uses memory-mapped files, when available on the host platform, resulting in a significant access speed-up.

This is correct when freetype is configured with the GNU Autotools. The implementation of streams for unix is located in `builds/unix/ftsystem.c`, which calls `open`. However it isn't correct when it is configured with CMake. The default implementation `src/base/ftsystem.c`, which calls `fopen`,  is used even when the platform is unix.

---

> Edit2: i did found that hooking "__fxstat" instead "fstat" does make all working fine, i'm not sure what's the problem thought.

In `/usr/include/x86_64-linux-gnu/sys/stat.h` on Ubuntu 20.04.
```c
/* To allow the `struct stat' structure and the file type `mode_t'
   bits to vary without changing shared library major version number,
   the `stat' family of functions and `mknod' are in fact inline
   wrappers around calls to `xstat', `fxstat', `lxstat', and `xmknod',
```
```c
__extern_inline int
__NTH (fstat (int __fd, struct stat *__statbuf))
{
  return __fxstat (_STAT_VER, __fd, __statbuf);
}
```

**Comment by kubo** [comment]
Closing.
I guess that it depends on whether freetype uses `src/base/ftsystem.c` or `builds/unix/ftsystem.c`.
