### ISSUE TITLE
Is there any plan to support 32-bit ARM?

### ISSUE THREAD

**Issue by LarryHuaLong** [kubo/funchook#34]
hi,I want to use this project on arm32 platform,but it seems not supported yet.What should I do to support arm32?
thanks.

**Comment by kubo** [comment]
Not at all.
I have no incentive to support it. Arm32 devices are being replaced by arm64.

**Comment by kubo** [comment]
I pushed [arm-thumb-abandoned branch](https://github.com/kubo/funchook/tree/arm-thumb-abandoned). See the [latest commit](https://github.com/kubo/funchook/commit/bb9734f675cf39a64439e5b56a77270778867adb). 

I don't know if the direction is correct. I did it about two years ago.
