### ISSUE TITLE
Can you add support for Windows ARM64?

### ISSUE THREAD

**Issue by dkjnsdvsodvnosdvm** [kubo/funchook#42]

**Comment by kubo** [comment]
I can but not sure when.

I guess that it works with or without small changes.
Linux arm64 is supported by using `funchook_unix.c` and `funchook_arm64.c`.
Windows x86/x64 is supported by using `funchook_windows.c` and `funchook_x86.c`.
I guess that it works on Windows arm64 by using `funchook_windows.c` and `funchook_arm64.c`.

**Comment by kubo** [comment]
I can't say anything about x64 or x86 programs on Windows arm64.

**Comment by kubo** [comment]
I added Windows arm64 support to version 1.1.2.
