### ISSUE TITLE
install hook on any address

### ISSUE THREAD

**Issue by zhangshuangjun** [kubo/funchook#46]
can i use funchook to install a hook on the address not only function begin?
like this:

send_func = (uchar*)send + 5;

**Comment by zhangshuangjun** [comment]
Okay, I test it. Thanks for your excellent job.

**Comment by zhangshuangjun** [comment]
Hi kubo,
I found there maybe a bug in funchook_hook_caller_asm:
".allocstack 0a0h"

In win64 os, Rsp should be alignment with 16. When hooked not at the begin of function,  the "allocstack 0a0h" cannot make sure the  alignment is all right, program will be crashed.

**Comment by zhangshuangjun** [comment]
movdqa need  128-bit memory location address

**Comment by zhangshuangjun** [comment]
It works, thanks.

**Comment by TheAhmad** [comment]
Hi,
IIUC, `funchook` hooks **function entries** and you will need to **re-execute** the original function at the end of the trampoline. If this is correct hooking **arbitrary** offsets seems **infeasible**. Other approaches such as using `Uprobe`s are **costly** and I found almost **no** other tool able to do this. I tried using [bpftime](https://github.com/eunomia-bpf/bpftime), but it is too **fragile** to work on real-world applications.

How can I **add** this functionality with the **least** amount of effort to the available tools such as `funchook` and **how long** does it take?
Regards.
