### ISSUE TITLE
Can we hook cpython?

### ISSUE THREAD

**Issue by houxinlin** [kubo/funchook#55]
I tried to write a C extension, but failed to hook after loading Python

Python Version:3.12
Os: Centos 7 

```python
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <funchook.h>
#include <stdio.h>

static PyObject *(*orig_PyUnicode_Format)(PyObject *format, PyObject *args) = NULL;

static PyObject *hooked_PyUnicode_Format(PyObject *format, PyObject *args) {
    printf("PyUnicode_Format is called with format: %s\n", PyUnicode_AsUTF8(format));

    return orig_PyUnicode_Format(format, args);
}

static int hook_PyUnicode_Format() {
    funchook_t *funchook = funchook_create();
    if (funchook == NULL) {
        return -1;
    }

    orig_PyUnicode_Format = (PyObject *(*)(PyObject *, PyObject *))PyUnicode_Format;

    if (funchook_prepare(funchook, (void **)&orig_PyUnicode_Format, (void *)hooked_PyUnicode_Format) != 0) {
        funchook_destroy(funchook);
        return -1;
    }

    if (funchook_install(funchook, 0) != 0) {
        funchook_destroy(funchook);
        return -1;
    }

    return 0;
}

static PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "myhook",
    "A module that hooks PyUnicode_Format",
    -1,
    NULL, NULL, NULL, NULL, NULL
};

PyMODINIT_FUNC PyInit_myhook(void) {
    if (hook_PyUnicode_Format() != 0) {
        return NULL;
    }

    return PyModule_Create(&moduledef);
}

```

```python
import myhook

print("test{0}".format("a"))

```
I hope to output PyUnicode Format is called with format:% s, but it doesn't work

**Comment by kubo** [comment]
> ```python
> import myhook
>
> print("test{0}".format("a"))
> ```
> 
> I hope to output PyUnicode Format is called with format:% s, but it doesn't work

The test code uses `str.format()`, which is different from `format_string % args`.
Could you test with the following code instead?

```python
import myhook

print("test%s" % "a")
```

**Comment by houxinlin** [comment]
It succeeded. I know this Python knowledge shouldn't be asked here, but I can't find the answer. Can I ask you?


How should I hook the format method so that when I execute print ("test {}". format ("a")), I can also hook it,

I tried some of the following functions, but none of them can hook up

https://github.com/python/cpython/blob/1dad23edbc9db3a13268c1000c8dd428edba29f8/PC/python3dll.c#L577

**Comment by kubo** [comment]
Here is an idea. I have not tested whether it is correct.

```c
for (const PyMethodDef *method = PyUnicode_Type->tp_methods; method->ml_name != NULL; method++) {
    if (strcmp(method->ml_name, "format") == 0) {
          ... hook method->ml_meth ...
    }
}
```

Though `method->ml_meth` is defined as `PyCFunction` [here](https://github.com/python/cpython/blob/v3.12.5/Include/methodobject.h#L56), its actual type depends on `method->ml_flags`.
See https://docs.python.org/3/c-api/structures.html#c.PyMethodDef and https://github.com/python/cpython/blob/v3.12.5/Objects/unicodeobject.c#L13438

**Comment by houxinlin** [comment]
Thank you very much, I have successfully hooked up
